import os

from dotenv import load_dotenv

load_dotenv()

POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT")
POSTGRES_DATABASE = os.environ.get("POSTGRES_DB")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")

DYNAMODB_REGION = os.environ.get("DYNAMODB_REGION")
DYNAMODB_TABLE_NAME = os.environ.get("DYNAMODB_TABLE_NAME")

RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.environ.get("RABBITMQ_PORT", "5672"))
RABBITMQ_USER = os.environ.get("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_PASSWORD")
RABBITMQ_QUEUE_NAME = os.environ.get("RABBITMQ_QUEUE_NAME")
RABBITMQ_QUEUE_NAME_ENV = os.environ.get("RABBITMQ_QUEUE_NAME_ENV")

AWS_ACCESS_KEY_ID_ENV = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY_ENV = os.environ.get("AWS_SECRET_ACCESS_KEY")

AWS_ACCESS_KEY_DYNAMODB = os.environ.get("AWS_ACCESS_KEY_DYNAMODB")
AWS_SECRET_ACCESS_KEY_DYNAMODB = os.environ.get("AWS_SECRET_ACCESS_KEY_DYNAMODB")

AWS_STORAGE_BUCKET_NAME_ENV = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME_ENV = os.environ.get("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN_ENV = os.environ.get("AWS_S3_CUSTOM_DOMAIN")
AWS_ALB_DOMAIN_ENV = os.environ.get("AWS_ALB_DOMAIN")
AWS_S3_ENDPOINT_URL_ENV = os.environ.get("AWS_S3_ENDPOINT_URL")
MINIO_ACCESS_URL_ENV = os.environ.get("MINIO_ACCESS_URL")

DYNAMODB_REGION_ENV = os.environ.get("DYNAMODB_REGION")
DYNAMODB_TABLE_NAME_ENV = os.environ.get("DYNAMODB_TABLE_NAME")


SNS_TOPIC_ARN = os.environ.get("SNS_TOPIC_ARN")

USE_S3_ENV = bool(os.environ.get("USE_S3", "false").upper() == "TRUE")

DEBUG_MODE = bool(os.environ.get("DEBUG_MODE", "false").upper() == "TRUE")

SERVICE_API_TOKEN = os.environ.get("SERVICE_API_TOKEN")
